apiVersion: apps/v1
kind: Deployment
metadata:
  name: meou-react
  namespace: meou
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: REACT_APP_SERVER_URL
              value: http://k8s-meou-meouclie-9eb11a035a-2040207942.us-east-2.elb.amazonaws.com
