apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: faisallarai/meou-client
    newName: faisallarai/meou-client
    newTag: main

patchesStrategicMerge:
  - custom-env.yaml
  - rollout-strategy.yaml
