apiVersion: apps/v1
kind: Deployment
metadata:
  name: meou-react
  namespace: meou
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
