apiVersion: apps/v1
kind: Deployment
metadata:
  name: meou-api
  namespace: meuo
  labels:
    app: meou-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meou-api
      tier: api
  template:
    metadata:
      labels:
        app: meou-api
        tier: api
    spec:
      containers:
        - name: app
          image: faisallarai/meou-api:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
