apiVersion: apps/v1
kind: Deployment
metadata:
  name: meou-api
  namespace: meou
  labels:
    app: meou-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meou-api
      tier: api
  template:
    metadata:
      labels:
        app: meou-api
        tier: api
    spec:
      containers:
        - name: app
          image: faisallarai/meou-api
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          imagePullPolicy: Always
      restartPolicy: Always
