apiVersion: v1
kind: Service
metadata:
  name: meou-api-service
  namespace: meou
  labels:
    app: meou-api
    tier: api
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 3000
      nodePort: 30036
      name: http
  selector:
    app: meou-api
    tier: api
