apiVersion: v1
kind: Service
metadata:
  name: meou-api-service
  namespace: meuo
  labels:
    app: meou-api
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: meou-api
    tier: api
