---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-mongodb
  namespace: meuo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
