apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-replica
  namespace: kube-system
spec:
  serviceName: 'mongo'
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        selector: mongo
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo
          command: ['/bin/sh']
          args: ['-c', 'mongod --replSet=rs0 --bind_ip_all']
          resources:
            limits:
              cpu: 1
              memory: 1500Mi
            requests:
              cpu: 1
              memory: 1000Mi
          ports:
            - name: mongo-port
              containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: 'role=mongo,environment=test'
  volumeClaimTemplates:
    - metadata:
        name: storage
        namespace: kube-system
        annotations:
          volume.alpha.kubernetes.io/storage-class: default
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 10Gi
