apiVersion: apps/v1
kind: Deployment
metadata:
  name: meou-api
  namespace: meuo
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: meou-api
                  key: redis-password
