apiVersion: v1
kind: Service
metadata:
  name: meou-react-service
  namespace: meuo
  labels:
    app: meou-react
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: meou-react
    tier: frontend
