apiVersion: v1
kind: Pod
metadata:
  name: redis-client
  namespace: meou
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: efs-claim-redis
  containers:
    - name: redis
      image: redis:6.2.3-alpine
      command: ['sh']
      args: ['-c', 'sleep infinity']
      volumeMounts:
        - mountPath: '/tmp'
          name: data
