apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: meou
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis
