apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-redis
  name: redis-service
  namespace: meou
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: server-port
  selector:
    app: app-redis
